name: Run Python Tests

on: [push, pull_request]  # Run on every push and every pull request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # Match your local Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest networkx  # Add any other packages you need

    - name: Run tests
      run: |
        PYTHONPATH=.:./graph_processing pytest graph_processing/tests --maxfail=1 --disable-warnings -q

